from django.conf import settings


ACCEPTANCE_SLA_MINUTES = int(getattr(settings, "ACCEPTANCE_SLA_MINUTES", 10))
REASSIGN_THRESHOLD_MINUTES = int(getattr(settings, "REASSIGN_THRESHOLD_MINUTES", 10))
ESCALATION_THRESHOLD_MINUTES = int(getattr(settings, "ESCALATION_THRESHOLD_MINUTES", 20))
SLA_WARNING_RATIO = float(getattr(settings, "SLA_WARNING_RATIO", 0.75))
REASSIGNMENT_RECENT_ASSIGNMENTS_WINDOW_MINUTES = int(
    getattr(settings, "REASSIGNMENT_RECENT_ASSIGNMENTS_WINDOW_MINUTES", 30)
)
REASSIGNMENT_MIN_SELECTION_SCORE = float(getattr(settings, "REASSIGNMENT_MIN_SELECTION_SCORE", 0.58))
REASSIGNMENT_SCORE_MARGIN = float(getattr(settings, "REASSIGNMENT_SCORE_MARGIN", 0.08))
