from django.urls import path

from .views import (
    ai_service_chat_proxy_view,
    assigned_tickets_view,
    assign_technician_view,
    change_password_view,
    consumable_detail_view,
    consumable_quantity_adjust_view,
    consumable_request_approve_view,
    consumable_request_reject_view,
    consumable_return_receive_view,
    consumable_return_reject_view,
    consumable_returns_collection_view,
    employee_detail_view,
    employees_collection_view,
    consumable_requests_collection_view,
    consumables_collection_view,
    performance_metrics_view,
    login_view,
    notifications_mark_read_view,
    notifications_view,
    technician_detail_view,
    technicians_collection_view,
    escalate_ticket_view,
    ticket_detail_view,
    ticket_material_requests_view,
    ticket_priority_view,
    ticket_status_view,
    tickets_collection_view,
)

urlpatterns = [
    path("auth/login", login_view),
    path("auth/change-password", change_password_view),
    path("ai-service/chat", ai_service_chat_proxy_view),
    path("tickets", tickets_collection_view),
    path("tickets/assigned/<int:technician_id>", assigned_tickets_view),
    path("tickets/<int:ticket_id>", ticket_detail_view),
    path("tickets/<int:ticket_id>/assign", assign_technician_view),
    path("tickets/<int:ticket_id>/escalate", escalate_ticket_view),
    path("tickets/<int:ticket_id>/material-requests", ticket_material_requests_view),
    path("tickets/<int:ticket_id>/priority", ticket_priority_view),
    path("tickets/<int:ticket_id>/status", ticket_status_view),
    path("technicians", technicians_collection_view),
    path("technicians/<int:technician_id>", technician_detail_view),
    path("employees", employees_collection_view),
    path("employees/<int:employee_id>", employee_detail_view),
    path("performance", performance_metrics_view),
    path("notifications", notifications_view),
    path("notifications/mark-read", notifications_mark_read_view),
    path("consumables", consumables_collection_view),
    path("consumables/<int:consumable_id>", consumable_detail_view),
    path("consumables/<int:consumable_id>/adjust", consumable_quantity_adjust_view),
    path("consumable-requests", consumable_requests_collection_view),
    path("consumable-requests/<int:request_id>/approve", consumable_request_approve_view),
    path("consumable-requests/<int:request_id>/reject", consumable_request_reject_view),
    path("consumable-returns", consumable_returns_collection_view),
    path("consumable-returns/<int:return_id>/receive", consumable_return_receive_view),
    path("consumable-returns/<int:return_id>/reject", consumable_return_reject_view),
]
