# pylint: disable=import-error
"""
AI service for classifying internal LEC IT support issues.

IMPORTANT RULES (LECIntelliSupport):
- Categories MUST be ONLY: HARDWARE, SOFTWARE, NETWORK
- Technician assignment must be based on CATEGORY.
  (AI predicts category; assignment selects a technician who handles that category.)
"""

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
import joblib
import numpy as np
from typing import List, Optional, Dict, Any
from pathlib import Path
import json
import re

app = FastAPI(title="LEC IntelliSupport AI")
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# -------------------------------------------------------------------
# Load trained models (generated by train_model.py)
# -------------------------------------------------------------------
vectorizer = joblib.load("models/vectorizer.joblib")
category_model = joblib.load("models/category_model.joblib")
severity_model = joblib.load("models/severity_model.joblib")
service_type_model = joblib.load("models/service_type_model.joblib")

ALLOWED_CATEGORIES = {"HARDWARE", "SOFTWARE", "NETWORK"}
STOPWORDS = {
    "the", "a", "an", "and", "or", "is", "are", "to", "for", "of", "on", "with", "in",
    "my", "me", "it", "this", "that", "i", "you", "we", "our", "can", "cannot", "cant",
    "not", "be", "from", "at", "by", "as", "after", "before", "today", "yesterday",
}
GREETING_TOKENS = {"hi", "hello", "hey", "yo", "hola", "morning", "afternoon", "evening", "greetings"}
COURTESY_TOKENS = {"thanks", "thank", "please", "assist", "help"}
ISSUE_SIGNAL_TOKENS = {
    "printer", "print", "paper", "jam", "offline", "toner", "cartridge",
    "internet", "wifi", "network", "dns", "vpn", "latency", "ip",
    "email", "outlook", "mailbox", "teams", "audio", "microphone", "speaker",
    "password", "reset", "login", "signin", "mfa", "authenticator", "otp",
    "rdp", "remote", "desktop", "drive", "server", "share", "file",
    "software", "install", "update", "browser", "app", "error", "failed",
    "keyboard", "mouse", "monitor", "display", "boot", "crash", "freeze",
}
KB_PRECISION_TOKENS = {"rdp", "mfa", "vpn", "outlook", "teams", "printer", "dns", "phishing", "bsod"}

KB_PATH = Path(__file__).resolve().parent / "data" / "helpdesk_kb.json"
with KB_PATH.open("r", encoding="utf-8") as kb_file:
    HELPDESK_KB = json.load(kb_file)
INTENTS_PATH = Path(__file__).resolve().parent / "data" / "intents.json"
with INTENTS_PATH.open("r", encoding="utf-8") as intents_file:
    INTENTS_DATA = json.load(intents_file).get("intents", [])

# -------------------------------------------------------------------
# Default technician mapping (fallback ONLY)
# In production, you'll pass technician list from backend.
# -------------------------------------------------------------------
TECHNICIAN_MAPPING = {
    "SOFTWARE": "Thabo Mokoena",
    "NETWORK": "Lerato Ndlovu",
    "HARDWARE": "Kabelo Phiri",
}
INTENT_CATEGORY_MAP = {
    "computer_not_turning_on": "HARDWARE",
    "slow_computer": "SOFTWARE",
    "printer_issue": "HARDWARE",
    "internet_problem": "NETWORK",
    "email_issue": "SOFTWARE",
    "keyboard_issue": "HARDWARE",
    "mouse_issue": "HARDWARE",
    "software_installation": "SOFTWARE",
    "password_reset": "SOFTWARE",
    "create_ticket": "SOFTWARE",
}
INTENT_HINT_TOKENS = {
    "internet_problem": {"internet", "wifi", "network", "dns", "vpn", "latency", "connection", "slow"},
    "slow_computer": {"computer", "pc", "laptop", "startup", "hang", "freeze", "performance"},
    "email_issue": {"email", "outlook", "mail", "smtp", "inbox"},
    "printer_issue": {"printer", "print", "paper", "jam", "offline"},
    "password_reset": {"password", "reset", "login", "account"},
}
NON_ISSUE_INTENTS = {"greeting", "thanks", "goodbye"}
CATEGORY_PLAYBOOK = {
    "HARDWARE": [
        "Verify the device has stable power and all cables are firmly connected.",
        "Restart the device and check whether status LEDs or startup beeps indicate hardware faults.",
        "Test with known-good peripherals or ports to isolate whether the issue is with the device or accessory.",
        "Record visible fault indicators (error text, blinking lights, serial number) before escalation.",
    ],
    "SOFTWARE": [
        "Restart the affected application and sign in again using the correct account.",
        "Clear temporary app/session data and confirm the device date/time and permissions are correct.",
        "Check for pending updates for the application and operating system, then retry the action.",
        "Capture the exact error message and the action that triggered it before escalation.",
    ],
    "NETWORK": [
        "Confirm the device is connected to the correct network and that link/Wi-Fi status is stable.",
        "Run a quick connectivity check (gateway/DNS/internet) to identify where communication fails.",
        "Reconnect network interface or restart router/switch path where possible and retry service access.",
        "Capture IP details, affected sites/apps, and outage scope (single user vs branch-wide) before escalation.",
    ],
}

class ClassifyRequest(BaseModel):
    text: str

class Technician(BaseModel):
    # keep it flexible for integration later
    id: Optional[str] = None
    name: str
    category: str  # HARDWARE / SOFTWARE / NETWORK
    open_tickets: int = 0

class AssignRequest(BaseModel):
    category: str
    technicians: List[Technician]

class ChatRequest(BaseModel):
    message: str


def _tokenize(text: str) -> set[str]:
    tokens = re.findall(r"[a-z0-9]+", text.lower())
    return {token for token in tokens if token not in STOPWORDS and len(token) > 2}


def _normalize_text(text: str) -> str:
    return re.sub(r"\s+", " ", re.sub(r"[^a-z0-9\s]", " ", text.lower())).strip()


def _tokens_with_stopwords(text: str) -> List[str]:
    return re.findall(r"[a-z0-9]+", text.lower())


def _contains_phrase(message_tokens: List[str], phrase_tokens: List[str]) -> bool:
    if not message_tokens or not phrase_tokens or len(phrase_tokens) > len(message_tokens):
        return False
    window = len(phrase_tokens)
    for idx in range(0, len(message_tokens) - window + 1):
        if message_tokens[idx:idx + window] == phrase_tokens:
            return True
    return False


def _match_intent(message: str) -> Optional[dict]:
    normalized_message = _normalize_text(message)
    if not normalized_message:
        return None

    message_words = _tokens_with_stopwords(normalized_message)
    message_tokens = _tokenize(normalized_message)
    best_intent = None
    best_score = 0.0

    for intent in INTENTS_DATA:
        intent_tag = str(intent.get("tag", "")).strip().lower()
        intent_best_score = 0.0
        for pattern in intent.get("patterns", []):
            normalized_pattern = _normalize_text(str(pattern))
            if not normalized_pattern:
                continue

            pattern_words = _tokens_with_stopwords(normalized_pattern)
            if not pattern_words:
                continue
            phrase_match = _contains_phrase(message_words, pattern_words)

            if phrase_match:
                score = 1.0 + min(0.6, 0.15 * len(pattern_words))
            else:
                pattern_tokens = _tokenize(normalized_pattern)
                if not pattern_tokens:
                    continue
                overlap = len(message_tokens.intersection(pattern_tokens))
                if overlap == 0:
                    continue
                score = overlap / max(len(pattern_tokens), 1)
                if intent_tag not in NON_ISSUE_INTENTS and overlap == 1 and len(pattern_tokens) > 1:
                    score -= 0.15

            hint_tokens = INTENT_HINT_TOKENS.get(intent_tag, set())
            if hint_tokens:
                hint_overlap = len(message_tokens.intersection(hint_tokens))
                if hint_overlap == 0 and intent_tag not in NON_ISSUE_INTENTS and not phrase_match:
                    score -= 0.25
                else:
                    score += min(0.45, hint_overlap * 0.15)

            if intent_tag == "slow_computer" and message_tokens.intersection({"internet", "wifi", "network", "dns", "vpn"}):
                score -= 0.25

            if score > intent_best_score:
                intent_best_score = score

        if intent_best_score > best_score:
            best_score = intent_best_score
            best_intent = intent

    if best_intent is None:
        return None

    best_tag = str(best_intent.get("tag", "")).strip().lower()
    if best_tag in NON_ISSUE_INTENTS:
        if len(message_tokens) > 3 or message_tokens.intersection(ISSUE_SIGNAL_TOKENS):
            return None
        if best_score < 0.75:
            return None
    elif best_score < 0.7:
        return None
    return best_intent


def _is_greeting_or_smalltalk(message: str) -> bool:
    normalized = re.sub(r"[^a-z0-9\s]", " ", message.lower()).strip()
    tokens = [token for token in normalized.split() if token]
    if not tokens:
        return True

    issue_tokens = _tokenize(normalized)
    if issue_tokens.intersection(ISSUE_SIGNAL_TOKENS):
        return False

    if len(tokens) <= 3 and all(token in GREETING_TOKENS.union(COURTESY_TOKENS) for token in tokens):
        return True

    smalltalk_patterns = (
        "how are you",
        "are you there",
        "can you help",
        "need help",
        "anyone there",
        "test",
    )
    return any(pattern in normalized for pattern in smalltalk_patterns) and len(tokens) <= 5


def _clarification_reply() -> str:
    return (
        "Hello. I can help you troubleshoot this professionally.\n"
        "Please share these details so I can give accurate steps:\n"
        "1. What is failing (app, device, printer, internet, email, etc.).\n"
        "2. Exact error message (if visible).\n"
        "3. Branch/location and how many users are affected.\n"
        "4. When the issue started and what changed recently."
    )


def _clean_instruction(text: str) -> str:
    cleaned = re.sub(r"__eou__|__eot__", " ", str(text), flags=re.IGNORECASE)
    cleaned = re.sub(r"\s+", " ", cleaned).strip(" -\t")
    if not cleaned:
        return ""
    return cleaned[0].upper() + cleaned[1:]


def _is_actionable_instruction(step: str) -> bool:
    lowered = step.lower().strip()
    if len(lowered) < 12:
        return False
    low_quality_signals = (
        "thats why i ask",
        "that's why i ask",
        "thank you",
        "thanks",
        "hi there",
        "hello there",
    )
    return not any(signal in lowered for signal in low_quality_signals)


def _merge_unique_steps(primary_steps: List[str], fallback_steps: List[str], limit: int = 4) -> List[str]:
    merged: List[str] = []
    seen = set()
    for raw_step in primary_steps + fallback_steps:
        step = _clean_instruction(raw_step)
        if not _is_actionable_instruction(step):
            continue
        key = step.lower()
        if key in seen:
            continue
        seen.add(key)
        merged.append(step)
        if len(merged) >= limit:
            break
    return merged


def _format_troubleshooting_reply(
    summary: str,
    category: str,
    steps: List[str],
    escalation: str,
    recommended_technician: str,
) -> str:
    numbered_steps = "\n".join([f"{idx}. {step}" for idx, step in enumerate(steps, start=1)])
    escalation_text = _clean_instruction(escalation) or "Escalate to Service Desk if unresolved."
    return (
        f"{summary} ({category})\n"
        "Troubleshooting steps:\n"
        f"{numbered_steps}\n"
        "Collect before escalation: exact error text, screenshot, affected users, and branch/location.\n"
        f"Escalation path: {recommended_technician}.\n"
        f"If unresolved: {escalation_text}"
    )


def _intent_issue_summary(tag: str) -> str:
    return f"{tag.replace('_', ' ').strip().title()} troubleshooting"


def _format_intent_issue_reply(intent: dict, category: str, recommended_technician: str) -> str:
    responses = [str(item) for item in intent.get("responses", []) if str(item).strip()]
    escalation = "Create a ticket manually with impact, location, and error details."
    troubleshooting_steps: List[str] = []

    for response in responses:
        cleaned = _clean_instruction(response)
        lower_response = cleaned.lower()
        if (
            "ticket" in lower_response or "support request" in lower_response or "support ticket" in lower_response
        ) and any(action in lower_response for action in ("submit", "request", "report", "create", "open", "escalate")):
            escalation = cleaned
            continue
        troubleshooting_steps.append(cleaned)

    steps = _merge_unique_steps(
        troubleshooting_steps,
        CATEGORY_PLAYBOOK.get(category, CATEGORY_PLAYBOOK["SOFTWARE"]),
    )
    if not steps:
        steps = CATEGORY_PLAYBOOK.get(category, CATEGORY_PLAYBOOK["SOFTWARE"])[:4]

    return _format_troubleshooting_reply(
        _intent_issue_summary(str(intent.get("tag", "issue"))),
        category,
        steps,
        escalation,
        recommended_technician,
    )


def _low_confidence_reply(category_hint: str) -> str:
    normalized_category = _normalize_category(category_hint)
    safe_category = normalized_category if normalized_category in ALLOWED_CATEGORIES else "SOFTWARE"
    queue_hint = TECHNICIAN_MAPPING.get(safe_category, "Service Desk")
    starter_steps = CATEGORY_PLAYBOOK.get(safe_category, CATEGORY_PLAYBOOK["SOFTWARE"])[:2]
    starter_steps_block = "\n".join([f"{idx}. {step}" for idx, step in enumerate(starter_steps, start=1)])
    return (
        "I need a bit more detail before I can give precise steps.\n"
        "Start with these checks:\n"
        f"{starter_steps_block}\n"
        "Please provide the exact symptom, error text, and affected system.\n"
        f"Current best category hint: {safe_category.title()} (queue: {queue_hint}).\n"
        "If business operations are blocked right now, proceed with manual fault reporting immediately."
    )


def _best_kb_article(message: str) -> Optional[dict]:
    normalized_message = _normalize_text(message)
    message_words = _tokens_with_stopwords(normalized_message)
    msg_tokens = _tokenize(message)
    if not msg_tokens:
        return None

    best_article = None
    best_score = 0
    best_phrase_bonus = -1
    best_overlap = -1

    for article in HELPDESK_KB:
        keyword_tokens = set()
        for keyword in article.get("keywords", []):
            keyword_tokens.update(_tokenize(keyword))
        keyword_tokens.update(_tokenize(article.get("title", "")))
        overlap = len(msg_tokens.intersection(keyword_tokens))

        # Prefer direct phrase matches if available
        phrase_bonus = 0
        for keyword in article.get("keywords", []):
            keyword_words = _tokens_with_stopwords(str(keyword))
            if _contains_phrase(message_words, keyword_words):
                phrase_bonus += 2
                if len(keyword_words) == 1 and keyword_words[0] in KB_PRECISION_TOKENS:
                    phrase_bonus += 2

        score = overlap + phrase_bonus
        if (
            score > best_score
            or (score == best_score and phrase_bonus > best_phrase_bonus)
            or (score == best_score and phrase_bonus == best_phrase_bonus and overlap > best_overlap)
        ):
            best_score = score
            best_phrase_bonus = phrase_bonus
            best_overlap = overlap
            best_article = article

    if best_score < 2:
        return None
    return best_article


def _format_kb_reply(article: dict, category: str, recommended_technician: str) -> str:
    normalized_category = _normalize_category(category)
    safe_category = normalized_category if normalized_category in ALLOWED_CATEGORIES else "SOFTWARE"
    article_steps = [str(item) for item in article.get("steps", [])]
    fallback_steps = CATEGORY_PLAYBOOK.get(safe_category, CATEGORY_PLAYBOOK["SOFTWARE"])
    merged_steps = _merge_unique_steps(article_steps, fallback_steps, limit=4)
    if not merged_steps:
        merged_steps = fallback_steps[:4]

    title = _clean_instruction(article.get("title", "Recommended troubleshooting actions"))
    escalation = str(article.get("escalation", "Escalate to service desk if issue remains unresolved."))
    return _format_troubleshooting_reply(
        title,
        safe_category,
        merged_steps,
        escalation,
        recommended_technician,
    )


def _generic_helpdesk_reply(category: str, recommended_technician: str) -> str:
    normalized_category = _normalize_category(category)
    safe_category = normalized_category if normalized_category in ALLOWED_CATEGORIES else "SOFTWARE"
    default_steps = CATEGORY_PLAYBOOK.get(safe_category, CATEGORY_PLAYBOOK["SOFTWARE"])[:4]
    return _format_troubleshooting_reply(
        "Recommended troubleshooting actions",
        safe_category,
        default_steps,
        "Create a ticket manually with impact, location, and error details.",
        recommended_technician,
    )

def _normalize_category(cat: str) -> str:
    if not cat:
        return ""
    c = cat.strip().upper()
    # allow some legacy lowercase
    if c in ["HARDWARE", "SOFTWARE", "NETWORK"]:
        return c
    # if a model still outputs lowercase for some reason
    c2 = cat.strip().lower()
    if c2 in ["hardware", "software", "network"]:
        return c2.upper()
    return c

def _pick_best_technician(category: str, technicians: List[Technician]) -> Optional[Technician]:
    # choose technicians whose category matches, then least open tickets
    matches = [t for t in technicians if _normalize_category(t.category) == category]
    if not matches:
        return None
    matches.sort(key=lambda t: (t.open_tickets, t.name.lower()))
    return matches[0]

@app.get("/health")
def health():
    return {"status": "ok", "allowed_categories": sorted(list(ALLOWED_CATEGORIES))}

@app.post("/classify")
def classify_issue(data: ClassifyRequest):
    text = (data.text or "").strip()
    if not text:
        return {"error": "Field 'text' is required"}

    vector = vectorizer.transform([text])

    raw_category = category_model.predict(vector)[0]
    category = _normalize_category(str(raw_category))

    # Enforce ONLY the 3 allowed categories
    if category not in ALLOWED_CATEGORIES:
        # Fallback mapping: if a legacy model leaks something else, default to SOFTWARE
        category = "SOFTWARE"

    severity = str(severity_model.predict(vector)[0]).strip().lower()
    service_type = str(service_type_model.predict(vector)[0]).strip().lower()

    confidence = None
    if hasattr(category_model, "predict_proba"):
        confidence = float(np.max(category_model.predict_proba(vector)))

    # Fallback technician recommendation (static)
    recommended_technician = TECHNICIAN_MAPPING.get(category, "Unassigned")

    return {
        "category": category,
        "severity": severity,
        "service_type": service_type,
        "recommended_technician": recommended_technician,
        "confidence": confidence,
    }

@app.post("/assign")
def assign_technician(data: AssignRequest) -> Dict[str, Any]:
    category = _normalize_category(data.category)
    if category not in ALLOWED_CATEGORIES:
        return {"error": f"category must be one of {sorted(list(ALLOWED_CATEGORIES))}"}

    # Only consider technicians that declare one of the allowed categories.
    valid_technicians = [t for t in data.technicians if _normalize_category(t.category) in ALLOWED_CATEGORIES]
    if not valid_technicians:
        return {
            "category": category,
            "assigned": None,
            "reason": "No technicians provided with valid categories (HARDWARE, SOFTWARE, NETWORK)",
        }

    best = _pick_best_technician(category, valid_technicians)
    if not best:
        return {"category": category, "assigned": None, "reason": "No technician matches category"}

    return {
        "category": category,
        "assigned": {
            "id": best.id,
            "name": best.name,
            "category": _normalize_category(best.category),
            "open_tickets": best.open_tickets,
        },
        "reason": "Matched by category and lowest workload",
    }


@app.post("/ai-service/chat")
def chat_helpdesk(data: ChatRequest) -> Dict[str, Any]:
    message = (data.message or "").strip()
    if not message:
        return {"reply": _clarification_reply(), "confidence": 0.0}

    intent = _match_intent(message)
    if intent is not None:
        intent_tag = str(intent.get("tag", "")).strip().lower()
        matched_intent_tag = intent_tag
        category = INTENT_CATEGORY_MAP.get(intent_tag, None)
        if category not in ALLOWED_CATEGORIES:
            category = None
        recommended_technician = TECHNICIAN_MAPPING.get(category, "Service Desk") if category else "Service Desk"
        if intent_tag in NON_ISSUE_INTENTS:
            responses = [str(item) for item in intent.get("responses", []) if str(item).strip()]
            reply = _clean_instruction(responses[0]) if responses else _clarification_reply()
        else:
            kb_article = _best_kb_article(message)
            if kb_article is not None:
                matched_intent_tag = str(kb_article.get("id", intent_tag)).strip().lower() or intent_tag
                kb_category = _normalize_category(str(kb_article.get("category", "")))
                safe_category = kb_category if kb_category in ALLOWED_CATEGORIES else (category if category in ALLOWED_CATEGORIES else "SOFTWARE")
                recommended_technician = TECHNICIAN_MAPPING.get(safe_category, "Service Desk")
                reply = _format_kb_reply(kb_article, safe_category, recommended_technician)
                category = safe_category
            else:
                safe_category = category if category in ALLOWED_CATEGORIES else "SOFTWARE"
                recommended_technician = TECHNICIAN_MAPPING.get(safe_category, "Service Desk")
                reply = _format_intent_issue_reply(intent, safe_category, recommended_technician)
                category = safe_category
        return {
            "reply": reply,
            "intent": matched_intent_tag,
            "category": category,
            "recommended_technician": recommended_technician,
            "confidence": 1.0,
        }

    if _is_greeting_or_smalltalk(message):
        return {
            "reply": _clarification_reply(),
            "category": None,
            "recommended_technician": "Service Desk",
            "confidence": 0.0,
        }

    if len(_tokenize(message)) < 2:
        return {
            "reply": _low_confidence_reply("SOFTWARE"),
            "category": "SOFTWARE",
            "recommended_technician": TECHNICIAN_MAPPING.get("SOFTWARE", "Service Desk"),
            "confidence": 0.0,
        }

    vector = vectorizer.transform([message])
    raw_category = category_model.predict(vector)[0]
    category = _normalize_category(str(raw_category))
    if category not in ALLOWED_CATEGORIES:
        category = "SOFTWARE"

    confidence = 0.0
    if hasattr(category_model, "predict_proba"):
        confidence = float(np.max(category_model.predict_proba(vector)))

    recommended_technician = TECHNICIAN_MAPPING.get(category, "Unassigned")
    article = _best_kb_article(message)

    if article is not None:
        article_category = _normalize_category(str(article.get("category", "")))
        safe_category = article_category if article_category in ALLOWED_CATEGORIES else category
        recommended_technician = TECHNICIAN_MAPPING.get(safe_category, "Service Desk")
        reply = _format_kb_reply(article, safe_category, recommended_technician)
        category = safe_category
        confidence = max(confidence, 0.78)
    elif confidence < 0.5:
        reply = _low_confidence_reply(category)
    else:
        reply = _generic_helpdesk_reply(category, recommended_technician)

    return {
        "reply": reply,
        "category": category,
        "recommended_technician": recommended_technician,
        "confidence": confidence,
    }
