# pylint: disable=import-error
"""
AI service for classifying internal LEC IT support issues.

IMPORTANT RULES (LECIntelliSupport):
- Categories MUST be ONLY: HARDWARE, SOFTWARE, NETWORK
- Technician assignment must be based on CATEGORY.
  (AI predicts category; assignment selects a technician who handles that category.)
"""

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
import joblib
import numpy as np
from typing import List, Optional, Dict, Any
from pathlib import Path
import json
import re

app = FastAPI(title="LEC IntelliSupport AI")
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# -------------------------------------------------------------------
# Load trained models (generated by train_model.py)
# -------------------------------------------------------------------
vectorizer = joblib.load("models/vectorizer.joblib")
category_model = joblib.load("models/category_model.joblib")
severity_model = joblib.load("models/severity_model.joblib")
service_type_model = joblib.load("models/service_type_model.joblib")

ALLOWED_CATEGORIES = {"HARDWARE", "SOFTWARE", "NETWORK"}
STOPWORDS = {
    "the", "a", "an", "and", "or", "is", "are", "to", "for", "of", "on", "with", "in",
    "my", "me", "it", "this", "that", "i", "you", "we", "our", "can", "cannot", "cant",
    "not", "be", "from", "at", "by", "as", "after", "before", "today", "yesterday",
}
GREETING_TOKENS = {"hi", "hello", "hey", "yo", "hola", "morning", "afternoon", "evening", "greetings"}
COURTESY_TOKENS = {"thanks", "thank", "please", "assist", "help"}

KB_PATH = Path(__file__).resolve().parent / "data" / "helpdesk_kb.json"
with KB_PATH.open("r", encoding="utf-8") as kb_file:
    HELPDESK_KB = json.load(kb_file)

# -------------------------------------------------------------------
# Default technician mapping (fallback ONLY)
# In production, you'll pass technician list from backend.
# -------------------------------------------------------------------
TECHNICIAN_MAPPING = {
    "SOFTWARE": "Thabo Mokoena",
    "NETWORK": "Lerato Ndlovu",
    "HARDWARE": "Kabelo Phiri",
}

class ClassifyRequest(BaseModel):
    text: str

class Technician(BaseModel):
    # keep it flexible for integration later
    id: Optional[str] = None
    name: str
    category: str  # HARDWARE / SOFTWARE / NETWORK
    open_tickets: int = 0

class AssignRequest(BaseModel):
    category: str
    technicians: List[Technician]

class ChatRequest(BaseModel):
    message: str


def _tokenize(text: str) -> set[str]:
    tokens = re.findall(r"[a-z0-9]+", text.lower())
    return {token for token in tokens if token not in STOPWORDS and len(token) > 2}


def _is_greeting_or_smalltalk(message: str) -> bool:
    normalized = re.sub(r"[^a-z0-9\s]", " ", message.lower()).strip()
    tokens = [token for token in normalized.split() if token]
    if not tokens:
        return True

    if len(tokens) <= 3 and all(token in GREETING_TOKENS.union(COURTESY_TOKENS) for token in tokens):
        return True

    smalltalk_patterns = (
        "how are you",
        "are you there",
        "can you help",
        "need help",
        "anyone there",
        "test",
    )
    return any(pattern in normalized for pattern in smalltalk_patterns) and len(tokens) <= 5


def _clarification_reply() -> str:
    return (
        "Hello. I can help you troubleshoot this professionally.\n"
        "Please share these details so I can give accurate steps:\n"
        "1. What is failing (app, device, printer, internet, email, etc.).\n"
        "2. Exact error message (if visible).\n"
        "3. Branch/location and how many users are affected.\n"
        "4. When the issue started and what changed recently."
    )


def _low_confidence_reply(category_hint: str) -> str:
    queue_hint = TECHNICIAN_MAPPING.get(category_hint, "Service Desk")
    return (
        "I need a bit more detail before I can give precise steps.\n"
        "Please provide the exact symptom, error text, and affected system.\n"
        f"Current best category hint: {category_hint.title()} (queue: {queue_hint}).\n"
        "If business operations are blocked right now, proceed with manual fault reporting immediately."
    )


def _best_kb_article(message: str) -> Optional[dict]:
    msg_tokens = _tokenize(message)
    if not msg_tokens:
        return None

    best_article = None
    best_score = 0

    for article in HELPDESK_KB:
        keyword_tokens = set()
        for keyword in article.get("keywords", []):
            keyword_tokens.update(_tokenize(keyword))
        keyword_tokens.update(_tokenize(article.get("title", "")))
        overlap = len(msg_tokens.intersection(keyword_tokens))

        # Prefer direct phrase matches if available
        phrase_bonus = 0
        lower_message = message.lower()
        for keyword in article.get("keywords", []):
            if keyword.lower() in lower_message:
                phrase_bonus += 2

        score = overlap + phrase_bonus
        if score > best_score:
            best_score = score
            best_article = article

    if best_score < 2:
        return None
    return best_article


def _format_kb_reply(article: dict, category: str) -> str:
    steps = article.get("steps", [])[:4]
    escalation = article.get("escalation", "Escalate to service desk if issue remains unresolved.")

    numbered_steps = "\n".join([f"{idx}. {step}" for idx, step in enumerate(steps, start=1)])
    return (
        f"{article.get('title')} ({category})\n"
        f"Try these steps:\n{numbered_steps}\n"
        f"If unresolved: {escalation}\n"
        "You can choose 'Create Ticket Manually' if the issue continues."
    )


def _generic_helpdesk_reply(category: str, recommended_technician: str) -> str:
    return (
        f"I understand this appears to be a {category.lower()} issue.\n"
        "Please try the following:\n"
        "1. Restart the affected app/device.\n"
        "2. Check network/power connection and retry.\n"
        "3. Capture any error message or screenshot.\n"
        f"Suggested technician queue: {recommended_technician}.\n"
        "If still unresolved, create a ticket manually with impact and location."
    )

def _normalize_category(cat: str) -> str:
    if not cat:
        return ""
    c = cat.strip().upper()
    # allow some legacy lowercase
    if c in ["HARDWARE", "SOFTWARE", "NETWORK"]:
        return c
    # if a model still outputs lowercase for some reason
    c2 = cat.strip().lower()
    if c2 in ["hardware", "software", "network"]:
        return c2.upper()
    return c

def _pick_best_technician(category: str, technicians: List[Technician]) -> Optional[Technician]:
    # choose technicians whose category matches, then least open tickets
    matches = [t for t in technicians if _normalize_category(t.category) == category]
    if not matches:
        return None
    matches.sort(key=lambda t: (t.open_tickets, t.name.lower()))
    return matches[0]

@app.get("/health")
def health():
    return {"status": "ok", "allowed_categories": sorted(list(ALLOWED_CATEGORIES))}

@app.post("/classify")
def classify_issue(data: ClassifyRequest):
    text = (data.text or "").strip()
    if not text:
        return {"error": "Field 'text' is required"}

    vector = vectorizer.transform([text])

    raw_category = category_model.predict(vector)[0]
    category = _normalize_category(str(raw_category))

    # Enforce ONLY the 3 allowed categories
    if category not in ALLOWED_CATEGORIES:
        # Fallback mapping: if a legacy model leaks something else, default to SOFTWARE
        category = "SOFTWARE"

    severity = str(severity_model.predict(vector)[0]).strip().lower()
    service_type = str(service_type_model.predict(vector)[0]).strip().lower()

    confidence = None
    if hasattr(category_model, "predict_proba"):
        confidence = float(np.max(category_model.predict_proba(vector)))

    # Fallback technician recommendation (static)
    recommended_technician = TECHNICIAN_MAPPING.get(category, "Unassigned")

    return {
        "category": category,
        "severity": severity,
        "service_type": service_type,
        "recommended_technician": recommended_technician,
        "confidence": confidence,
    }

@app.post("/assign")
def assign_technician(data: AssignRequest) -> Dict[str, Any]:
    category = _normalize_category(data.category)
    if category not in ALLOWED_CATEGORIES:
        return {"error": f"category must be one of {sorted(list(ALLOWED_CATEGORIES))}"}

    # Only consider technicians that declare one of the allowed categories.
    valid_technicians = [t for t in data.technicians if _normalize_category(t.category) in ALLOWED_CATEGORIES]
    if not valid_technicians:
        return {
            "category": category,
            "assigned": None,
            "reason": "No technicians provided with valid categories (HARDWARE, SOFTWARE, NETWORK)",
        }

    best = _pick_best_technician(category, valid_technicians)
    if not best:
        return {"category": category, "assigned": None, "reason": "No technician matches category"}

    return {
        "category": category,
        "assigned": {
            "id": best.id,
            "name": best.name,
            "category": _normalize_category(best.category),
            "open_tickets": best.open_tickets,
        },
        "reason": "Matched by category and lowest workload",
    }


@app.post("/ai-service/chat")
def chat_helpdesk(data: ChatRequest) -> Dict[str, Any]:
    message = (data.message or "").strip()
    if not message:
        return {"reply": _clarification_reply(), "confidence": 0.0}

    if _is_greeting_or_smalltalk(message):
        return {
            "reply": _clarification_reply(),
            "category": None,
            "recommended_technician": "Service Desk",
            "confidence": 0.0,
        }

    if len(_tokenize(message)) < 2:
        return {
            "reply": _low_confidence_reply("SOFTWARE"),
            "category": "SOFTWARE",
            "recommended_technician": TECHNICIAN_MAPPING.get("SOFTWARE", "Service Desk"),
            "confidence": 0.0,
        }

    vector = vectorizer.transform([message])
    raw_category = category_model.predict(vector)[0]
    category = _normalize_category(str(raw_category))
    if category not in ALLOWED_CATEGORIES:
        category = "SOFTWARE"

    confidence = 0.0
    if hasattr(category_model, "predict_proba"):
        confidence = float(np.max(category_model.predict_proba(vector)))

    recommended_technician = TECHNICIAN_MAPPING.get(category, "Unassigned")
    article = _best_kb_article(message)

    if article is not None:
        reply = _format_kb_reply(article, article.get("category", category))
    elif confidence < 0.5:
        reply = _low_confidence_reply(category)
    else:
        reply = _generic_helpdesk_reply(category, recommended_technician)

    return {
        "reply": reply,
        "category": category,
        "recommended_technician": recommended_technician,
        "confidence": confidence,
    }
