# Generated by Django 5.2.12 on 2026-03-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumable',
            name='assigned_employee',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='consumable',
            name='department',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
