# Generated by Django 5.2.12 on 2026-03-05 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_consumable_assigned_employee_consumable_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumableRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('department', models.CharField(blank=True, default='', max_length=120)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_consumable_requests', to='core.user')),
                ('consumable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='core.consumable')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumable_requests', to='core.user')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_consumable_requests', to='core.user')),
            ],
            options={
                'db_table': 'consumable_requests',
            },
        ),
    ]
