# Generated by Django 5.2.12 on 2026-03-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_ticketmaterialrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="consumable",
            name="asset_tag",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="consumable",
            name="manufacturer",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="consumable",
            name="brand",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="consumable",
            name="model_number",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="consumable",
            name="serial_number",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="consumable",
            name="category",
            field=models.CharField(blank=True, default="", max_length=60),
        ),
        migrations.AddField(
            model_name="consumable",
            name="subcategory",
            field=models.CharField(blank=True, default="", max_length=60),
        ),
        migrations.AddField(
            model_name="consumable",
            name="processor",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="consumable",
            name="ram",
            field=models.CharField(blank=True, default="", max_length=60),
        ),
        migrations.AddField(
            model_name="consumable",
            name="storage_type",
            field=models.CharField(blank=True, default="", max_length=60),
        ),
        migrations.AddField(
            model_name="consumable",
            name="storage_capacity",
            field=models.CharField(blank=True, default="", max_length=60),
        ),
        migrations.AddField(
            model_name="consumable",
            name="graphics_card",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="consumable",
            name="charger_included",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="consumable",
            name="monitor_included",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="consumable",
            name="keyboard_included",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="consumable",
            name="mouse_included",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="consumable",
            name="printer_type",
            field=models.CharField(blank=True, default="", max_length=60),
        ),
        migrations.AddField(
            model_name="consumable",
            name="print_speed",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.AddField(
            model_name="consumable",
            name="connectivity",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="consumable",
            name="duplex_printing",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="consumable",
            name="paper_capacity",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.AddField(
            model_name="consumable",
            name="color_printing",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="consumable",
            name="device_type",
            field=models.CharField(blank=True, default="", max_length=60),
        ),
        migrations.AddField(
            model_name="consumable",
            name="operating_system",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="consumable",
            name="battery_capacity",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.AddField(
            model_name="consumable",
            name="imei_number",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="consumable",
            name="purchase_cost",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name="consumable",
            name="supplier",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="consumable",
            name="warranty_expiry",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="consumable",
            name="purchase_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="consumable",
            name="condition",
            field=models.CharField(blank=True, default="", max_length=60),
        ),
        migrations.AddField(
            model_name="consumable",
            name="status",
            field=models.CharField(blank=True, default="", max_length=60),
        ),
    ]
