# Generated by Django 5.2.12 on 2026-03-12 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_consumablerequest_assignment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='caller_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='ticket',
            name='logged_by_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logged_call_tickets', to='core.user'),
        ),
    ]
