# Generated by Codex on 2026-03-13

from datetime import date
from decimal import Decimal

from django.db import migrations


def seed_consumable_inventory_data(apps, schema_editor):
    Consumable = apps.get_model("core", "Consumable")

    seed_rows = [
        {
            "item_name": "laptops",
            "asset_tag": "LEC-CMP-BULK-LPT",
            "manufacturer": "Dell",
            "brand": "Dell",
            "model_number": "Latitude 5440",
            "serial_number": "BULK-LPT-2026",
            "category": "Computer",
            "subcategory": "Laptop",
            "processor": "Intel Core i7",
            "ram": "16 GB",
            "storage_type": "SSD",
            "storage_capacity": "512 GB",
            "graphics_card": "Integrated",
            "charger_included": True,
            "quantity": 28,
            "purchase_cost": Decimal("18500.00"),
            "supplier": "TechHub Lesotho",
            "warranty_expiry": date(2028, 12, 31),
            "purchase_date": date(2026, 1, 15),
            "condition": "New",
            "status": "In Stock",
            "department": "Finance",
            "assigned_employee": "Shared",
        },
        {
            "item_name": "cartridges",
            "asset_tag": "LEC-PRN-BULK-CRT",
            "manufacturer": "HP",
            "brand": "HP",
            "model_number": "305A Black Toner",
            "serial_number": "BULK-CRT-2026",
            "category": "Printer",
            "subcategory": "Laser",
            "printer_type": "Laser",
            "quantity": 64,
            "purchase_cost": Decimal("950.00"),
            "supplier": "Office Supplies Co.",
            "purchase_date": date(2026, 2, 1),
            "condition": "New",
            "status": "In Stock",
            "department": "Operations",
            "assigned_employee": "Shared",
        },
        {
            "item_name": "paper",
            "asset_tag": "LEC-PRN-BULK-PPR",
            "manufacturer": "Mondi",
            "brand": "Mondi",
            "model_number": "A4 80gsm Ream",
            "serial_number": "BULK-PPR-2026",
            "category": "Printer Supplies",
            "subcategory": "Paper",
            "quantity": 420,
            "purchase_cost": Decimal("85.00"),
            "supplier": "Stationery World",
            "purchase_date": date(2026, 2, 10),
            "condition": "New",
            "status": "In Stock",
            "department": "Admin",
            "assigned_employee": "Shared",
        },
        {
            "item_name": "mouse",
            "asset_tag": "LEC-GDT-BULK-MSE",
            "manufacturer": "Logitech",
            "brand": "Logitech",
            "model_number": "M185",
            "serial_number": "BULK-MSE-2026",
            "category": "Gadget",
            "subcategory": "Mouse",
            "device_type": "Mouse",
            "quantity": 84,
            "purchase_cost": Decimal("180.00"),
            "supplier": "Peripheral Source",
            "purchase_date": date(2026, 2, 12),
            "condition": "New",
            "status": "In Stock",
            "department": "Contact Center",
            "assigned_employee": "Shared",
        },
        {
            "item_name": "keyboard",
            "asset_tag": "LEC-GDT-BULK-KBD",
            "manufacturer": "Logitech",
            "brand": "Logitech",
            "model_number": "K120",
            "serial_number": "BULK-KBD-2026",
            "category": "Gadget",
            "subcategory": "Keyboard",
            "device_type": "Keyboard",
            "quantity": 71,
            "purchase_cost": Decimal("250.00"),
            "supplier": "Peripheral Source",
            "purchase_date": date(2026, 2, 12),
            "condition": "New",
            "status": "In Stock",
            "department": "Engineering",
            "assigned_employee": "Shared",
        },
    ]

    protected_fields = {"quantity", "purchase_cost", "purchase_date", "warranty_expiry"}

    for row in seed_rows:
        item_name = row["item_name"]
        existing = Consumable.objects.filter(item_name=item_name).order_by("id").first()

        if existing:
            update_fields = []
            for field_name, default_value in row.items():
                if field_name == "item_name":
                    continue

                current_value = getattr(existing, field_name, None)

                if field_name == "quantity":
                    if not current_value or current_value <= 0:
                        setattr(existing, field_name, default_value)
                        update_fields.append(field_name)
                    continue

                if field_name in protected_fields:
                    if current_value is None:
                        setattr(existing, field_name, default_value)
                        update_fields.append(field_name)
                    continue

                if current_value is None or (isinstance(current_value, str) and not current_value.strip()):
                    setattr(existing, field_name, default_value)
                    update_fields.append(field_name)

            if update_fields:
                existing.save(update_fields=sorted(set(update_fields + ["updated_at"])))
        else:
            Consumable.objects.create(**row)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_ticket_caller_name_ticket_logged_by_admin_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_consumable_inventory_data, migrations.RunPython.noop),
    ]

