# Generated by Codex on 2026-03-13

from datetime import date
from decimal import Decimal

from django.db import migrations


def seed_pool_inventory_data(apps, schema_editor):
    Consumable = apps.get_model("core", "Consumable")

    seed_rows = [
        {
            "asset_tag": "LEC-LTP-POOL-001",
            "item_name": "Laptop Dell Latitude 5440",
            "manufacturer": "Dell",
            "brand": "Dell",
            "model_number": "Latitude 5440",
            "serial_number": "DL5440-POOL-001",
            "category": "Computer",
            "subcategory": "Laptop",
            "processor": "Intel Core i5",
            "ram": "16 GB",
            "storage_type": "SSD",
            "storage_capacity": "512 GB",
            "graphics_card": "Integrated",
            "charger_included": True,
            "quantity": 28,
            "purchase_cost": Decimal("18500.00"),
            "supplier": "Mustek",
            "purchase_date": date(2025, 1, 15),
            "warranty_expiry": date(2028, 1, 15),
            "condition": "New",
            "status": "In Stock",
        },
        {
            "asset_tag": "LEC-PRC-POOL-002",
            "item_name": "Printer Cartridge HP 415A Black",
            "manufacturer": "HP",
            "brand": "HP",
            "model_number": "415A",
            "serial_number": "HP415A-POOL-002",
            "category": "Printer",
            "subcategory": "Laser",
            "printer_type": "Laser",
            "print_speed": "40 ppm",
            "connectivity": "USB / Ethernet",
            "paper_capacity": "500 sheets",
            "color_printing": False,
            "quantity": 62,
            "purchase_cost": Decimal("1450.00"),
            "supplier": "Office Warehouse",
            "purchase_date": date(2025, 2, 10),
            "warranty_expiry": date(2027, 2, 10),
            "condition": "New",
            "status": "In Stock",
        },
        {
            "asset_tag": "LEC-PAP-POOL-003",
            "item_name": "A4 Copy Paper Typek 80gsm",
            "manufacturer": "Typek",
            "brand": "Typek",
            "model_number": "A4-80GSM-500",
            "serial_number": "TKA4-POOL-003",
            "category": "Stationery",
            "subcategory": "Paper",
            "quantity": 299,
            "purchase_cost": Decimal("95.00"),
            "supplier": "Office Warehouse",
            "purchase_date": date(2025, 2, 1),
            "warranty_expiry": date(2027, 2, 1),
            "condition": "New",
            "status": "In Stock",
        },
        {
            "asset_tag": "LEC-MOU-POOL-004",
            "item_name": "Wireless Mouse Logitech M185",
            "manufacturer": "Logitech",
            "brand": "Logitech",
            "model_number": "M185",
            "serial_number": "LGM185-POOL-004",
            "category": "Gadget",
            "subcategory": "Mouse",
            "device_type": "Mouse",
            "connectivity": "USB",
            "battery_capacity": "AA",
            "quantity": 84,
            "purchase_cost": Decimal("220.00"),
            "supplier": "First Distribution",
            "purchase_date": date(2025, 3, 5),
            "warranty_expiry": date(2027, 3, 5),
            "condition": "New",
            "status": "In Stock",
        },
        {
            "asset_tag": "LEC-KBD-POOL-005",
            "item_name": "Keyboard Logitech K120",
            "manufacturer": "Logitech",
            "brand": "Logitech",
            "model_number": "K120",
            "serial_number": "LGK120-POOL-005",
            "category": "Gadget",
            "subcategory": "Keyboard",
            "device_type": "Keyboard",
            "connectivity": "USB",
            "quantity": 70,
            "purchase_cost": Decimal("280.00"),
            "supplier": "First Distribution",
            "purchase_date": date(2025, 3, 5),
            "warranty_expiry": date(2027, 3, 5),
            "condition": "New",
            "status": "In Stock",
        },
    ]

    protected_fields = {"quantity", "purchase_cost", "purchase_date", "warranty_expiry"}

    for row in seed_rows:
        asset_tag = row["asset_tag"]
        existing = Consumable.objects.filter(asset_tag=asset_tag).order_by("id").first()

        if existing:
            update_fields = []
            for field_name, default_value in row.items():
                if field_name == "asset_tag":
                    continue

                current_value = getattr(existing, field_name, None)

                if field_name == "quantity":
                    if not current_value or current_value <= 0:
                        setattr(existing, field_name, default_value)
                        update_fields.append(field_name)
                    continue

                if field_name in protected_fields:
                    if current_value is None:
                        setattr(existing, field_name, default_value)
                        update_fields.append(field_name)
                    continue

                if current_value is None or (isinstance(current_value, str) and not current_value.strip()):
                    setattr(existing, field_name, default_value)
                    update_fields.append(field_name)

            if update_fields:
                existing.save(update_fields=sorted(set(update_fields + ["updated_at"])))
        else:
            Consumable.objects.create(**row)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_seed_consumable_inventory_data"),
    ]

    operations = [
        migrations.RunPython(seed_pool_inventory_data, migrations.RunPython.noop),
    ]

