# Generated by Django 5.2.12 on 2026-04-15 10:16

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_technician_department_and_hq_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Business Hours', max_length=120)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('timezone_name', models.CharField(default='Africa/Johannesburg', max_length=64)),
                ('groups', models.JSONField(default=core.models.default_business_hours_groups)),
                ('weekly_schedule', models.JSONField(default=core.models.default_business_hours_schedule)),
                ('is_default', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'business_hours',
            },
        ),
        migrations.CreateModel(
            name='BusinessHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_hours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='core.businesshours')),
            ],
            options={
                'db_table': 'business_holidays',
                'constraints': [models.UniqueConstraint(fields=('business_hours', 'date'), name='unique_business_holiday_per_day')],
            },
        ),
    ]
