# Generated by Django 5.2.12 on 2026-04-15 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_businesshours_businessholiday'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('annual', 'Annual Leave'), ('sick', 'Sick Leave'), ('study', 'Study Leave'), ('unpaid', 'Unpaid Leave'), ('other', 'Other')], default='annual', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_hours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='core.businesshours')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_leaves', to='core.technician')),
            ],
            options={
                'db_table': 'business_leaves',
            },
        ),
    ]
