# Generated by Django 5.2.12 on 2026-04-21 19:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_merge_20260417_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='assigned_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ticket',
            name='escalation_level',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='reassign_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='TicketAssignmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('auto_assign', 'Auto Assign'), ('auto_reassign', 'Auto Reassign'), ('admin_escalation', 'Admin Escalation'), ('technician_escalation', 'Technician Escalation'), ('manual', 'Manual')], default='auto_assign', max_length=32)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_history', to='core.technician')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_history', to='core.ticket')),
            ],
            options={
                'db_table': 'ticket_assignment_history',
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['ticket', 'assigned_at'], name='tasg_ticket_at_idx'), models.Index(fields=['technician', 'assigned_at'], name='tasg_tech_at_idx')],
            },
        ),
    ]
