# Generated by Django 5.2.12 on 2026-05-28 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_consumablerequest_return_reminders'),
        ('core', '0032_user_department'),
    ]

    operations = [
    ]
