# Generated by Django on 2026-05-31

import django.db.models.deletion
from django.db import migrations, models


def add_ticket_channel_if_missing(apps, schema_editor):
    table_name = "tickets"
    with schema_editor.connection.cursor() as cursor:
        existing_columns = {
            column.name
            for column in schema_editor.connection.introspection.get_table_description(cursor, table_name)
        }
    if "channel" in existing_columns:
        return

    Ticket = apps.get_model("core", "Ticket")
    field = models.CharField(blank=True, default="manual", max_length=32)
    field.set_attributes_from_name("channel")
    schema_editor.add_field(Ticket, field)


PROBLEM_SEEDS = [
    {
        "asset_type": "Paper",
        "asset_category": "Paper",
        "title": "Paper stock finished",
        "description": "Paper cannot be used because the expected stock is empty or unavailable.",
        "steps": [
            "Check the physical paper tray or storage area.",
            "Confirm whether sealed paper packages are available.",
            "Confirm the asset code matches the scanned paper stock.",
            "Check if another department recently collected the paper.",
            "If paper is available, update the issue as resolved.",
        ],
    },
    {
        "asset_type": "Paper",
        "asset_category": "Paper",
        "title": "Wrong paper loaded",
        "description": "The wrong size, type, or department paper stock appears to be loaded.",
        "steps": [
            "Check the paper size and label on the package.",
            "Compare it with the required paper type for the device or department.",
            "Remove incorrect paper from the tray or storage area.",
            "Load the correct paper and keep the packaging label visible.",
        ],
    },
    {
        "asset_type": "Paper",
        "asset_category": "Paper",
        "title": "Paper not recorded in stock",
        "description": "Paper exists physically but does not appear correctly in stock records.",
        "steps": [
            "Count the available sealed and opened paper packages.",
            "Confirm the scanned asset code matches the physical stock label.",
            "Check whether stock was recently moved between departments.",
            "Record the corrected quantity if you have stock update access.",
        ],
    },
    {
        "asset_type": "Paper",
        "asset_category": "Paper",
        "title": "Damaged paper package",
        "description": "Paper packaging or sheets are damaged and may not be usable.",
        "steps": [
            "Inspect the package for water, dust, tears, or bending.",
            "Separate damaged sheets from usable paper.",
            "Check whether another sealed package is available.",
            "Keep the damaged package aside for consumables review.",
        ],
    },
    {
        "asset_type": "Printer",
        "asset_category": "Printer",
        "title": "Paper jam",
        "description": "The printer reports a jam or paper is visibly stuck.",
        "steps": [
            "Power off the printer before opening trays or panels.",
            "Open the indicated tray or rear access panel.",
            "Remove stuck paper slowly in the paper path direction.",
            "Reload paper neatly and close all panels.",
            "Power on the printer and print a test page.",
        ],
    },
    {
        "asset_type": "Printer",
        "asset_category": "Printer",
        "title": "Printer offline",
        "description": "The printer is powered on but shows offline or unavailable.",
        "steps": [
            "Confirm the printer is powered on and ready.",
            "Check the USB, LAN, or Wi-Fi connection.",
            "Confirm the correct printer is selected on the workstation.",
            "Restart the printer and wait for it to reconnect.",
            "Try printing a test page.",
        ],
    },
    {
        "asset_type": "Printer",
        "asset_category": "Printer",
        "title": "Low toner",
        "description": "The printer warns about toner or print output is faded.",
        "steps": [
            "Check the toner level on the printer display.",
            "Remove and gently reseat the toner cartridge.",
            "Check whether a replacement cartridge is available.",
            "Print a test page after reseating or replacing toner.",
        ],
    },
    {
        "asset_type": "Printer",
        "asset_category": "Printer",
        "title": "Poor print quality",
        "description": "Printed pages are faded, streaked, smudged, or misaligned.",
        "steps": [
            "Check paper type and confirm it is dry and undamaged.",
            "Run the printer cleaning or calibration option if available.",
            "Check toner or ink levels.",
            "Print a test page to confirm whether quality improves.",
        ],
    },
    {
        "asset_type": "Printer",
        "asset_category": "Printer",
        "title": "Cannot connect to printer",
        "description": "A workstation cannot find or connect to the printer.",
        "steps": [
            "Confirm the printer is connected to the same network.",
            "Check the printer IP address or shared printer name.",
            "Restart the printer and workstation if safe to do so.",
            "Try adding the printer again from the workstation.",
        ],
    },
    {
        "asset_type": "Router",
        "asset_category": "Network",
        "title": "No internet connection",
        "description": "Users connected through this router cannot reach the internet.",
        "steps": [
            "Check power and internet/link indicator lights.",
            "Confirm upstream cable is firmly connected.",
            "Test internet access from another device.",
            "Restart the router if business impact allows it.",
            "Wait for link lights to stabilize and retest.",
        ],
    },
    {
        "asset_type": "Router",
        "asset_category": "Network",
        "title": "Slow connection",
        "description": "Network access works but is unusually slow.",
        "steps": [
            "Check if multiple users are affected.",
            "Test a wired connection if available.",
            "Check router temperature and indicator lights.",
            "Restart the router if approved for the location.",
            "Retest a known business application.",
        ],
    },
    {
        "asset_type": "Router",
        "asset_category": "Network",
        "title": "Power issue",
        "description": "The router does not power on or loses power.",
        "steps": [
            "Check the wall socket or UPS output.",
            "Confirm the power adapter is firmly connected.",
            "Look for damaged adapter or cable marks.",
            "Try a known working outlet if safe.",
        ],
    },
    {
        "asset_type": "Router",
        "asset_category": "Network",
        "title": "Loose cable",
        "description": "A loose network or power cable may be interrupting service.",
        "steps": [
            "Inspect WAN, LAN, and power cables.",
            "Push each connector in until it clicks or seats firmly.",
            "Check link lights after reseating cables.",
            "Replace the cable if the connector is damaged.",
        ],
    },
    {
        "asset_type": "Router",
        "asset_category": "Network",
        "title": "Device overheating",
        "description": "The router feels hot or is in a poorly ventilated area.",
        "steps": [
            "Check whether air vents are blocked.",
            "Move papers or equipment away from the router.",
            "Confirm the device is not in direct sunlight.",
            "Allow it to cool and retest network access.",
        ],
    },
    {
        "asset_type": "",
        "asset_category": "Computer",
        "title": "Laptop or computer will not power on",
        "description": "The device does not start or shows no power indicators.",
        "steps": [
            "Check the charger or power cable connection.",
            "Confirm the wall socket or docking station has power.",
            "Hold the power button for ten seconds, then try again.",
            "Remove non-essential USB devices and retry startup.",
        ],
    },
    {
        "asset_type": "",
        "asset_category": "Computer",
        "title": "Very slow performance",
        "description": "The computer responds slowly or applications take too long to open.",
        "steps": [
            "Close unused applications and browser tabs.",
            "Restart the computer if it is safe to do so.",
            "Check whether storage is nearly full.",
            "Confirm antivirus or updates are not actively running.",
        ],
    },
    {
        "asset_type": "",
        "asset_category": "Computer",
        "title": "Cannot connect to network",
        "description": "The computer cannot access Wi-Fi, LAN, or internal systems.",
        "steps": [
            "Check Wi-Fi or LAN cable connection.",
            "Confirm airplane mode is off.",
            "Reconnect to the approved LEC network.",
            "Restart the device and test a known internal system.",
        ],
    },
    {
        "asset_type": "",
        "asset_category": "Computer",
        "title": "Application not opening",
        "description": "A required application fails to launch or closes immediately.",
        "steps": [
            "Close and reopen the application.",
            "Restart the computer if the application remains stuck.",
            "Check whether another user can open the same application.",
            "Note any error message shown on screen.",
        ],
    },
    {
        "asset_type": "",
        "asset_category": "Computer",
        "title": "Device overheating",
        "description": "The computer becomes unusually hot or the fan runs constantly.",
        "steps": [
            "Check that air vents are not blocked.",
            "Move the device to a flat ventilated surface.",
            "Close heavy applications and wait a few minutes.",
            "Restart the device if performance remains poor.",
        ],
    },
    {
        "asset_type": "UPS",
        "asset_category": "Power",
        "title": "UPS not providing backup power",
        "description": "The UPS does not keep connected equipment running during power loss.",
        "steps": [
            "Confirm the UPS is switched on.",
            "Check battery or fault indicator lights.",
            "Confirm critical devices are plugged into battery-backed outlets.",
            "Run a brief self-test if the UPS supports it.",
        ],
    },
    {
        "asset_type": "UPS",
        "asset_category": "Power",
        "title": "UPS alarm beeping",
        "description": "The UPS is making an audible alarm.",
        "steps": [
            "Check the display or indicator light meaning.",
            "Confirm the UPS is not overloaded.",
            "Check whether mains power is available.",
            "Remove non-critical loads and observe whether the alarm clears.",
        ],
    },
    {
        "asset_type": "Switch",
        "asset_category": "Network",
        "title": "Switch port not working",
        "description": "A network switch port has no link or cannot pass traffic.",
        "steps": [
            "Check the port link light.",
            "Reseat the Ethernet cable on both ends.",
            "Try a known working cable.",
            "Move the device to another approved port and retest.",
        ],
    },
    {
        "asset_type": "Switch",
        "asset_category": "Network",
        "title": "Multiple users disconnected",
        "description": "Several users connected to the switch lost network access.",
        "steps": [
            "Check switch power and uplink lights.",
            "Confirm the uplink cable is firmly connected.",
            "Check if only one area or all users are affected.",
            "Restart only if approved for the affected area.",
        ],
    },
    {
        "asset_type": "Server",
        "asset_category": "Infrastructure",
        "title": "Server service unavailable",
        "description": "A service hosted by the server cannot be reached.",
        "steps": [
            "Confirm the server has power and normal indicator lights.",
            "Check whether other services on the same server are reachable.",
            "Confirm network cable/link lights are active.",
            "Record the service name and exact error message.",
        ],
    },
    {
        "asset_type": "Server",
        "asset_category": "Infrastructure",
        "title": "Server storage warning",
        "description": "The server reports low disk space or a storage alert.",
        "steps": [
            "Capture the exact storage warning.",
            "Check if any scheduled backup or export is running.",
            "Do not delete files without authorization.",
            "Record affected service and urgency for escalation.",
        ],
    },
]


def seed_asset_troubleshooting_data(apps, schema_editor):
    AssetCommonProblem = apps.get_model("core", "AssetCommonProblem")
    TroubleshootingStep = apps.get_model("core", "TroubleshootingStep")

    for item in PROBLEM_SEEDS:
        problem, _created = AssetCommonProblem.objects.update_or_create(
            asset_type=item["asset_type"],
            asset_category=item["asset_category"],
            title=item["title"],
            defaults={
                "description": item["description"],
                "is_active": True,
            },
        )
        problem.steps.all().delete()
        for index, instruction in enumerate(item["steps"], start=1):
            TroubleshootingStep.objects.create(
                problem=problem,
                step_number=index,
                instruction=instruction,
                is_active=True,
            )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_merge_whatsapp_intake"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="asset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fault_tickets",
                to="core.consumable",
            ),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_ticket_channel_if_missing, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="ticket",
                    name="channel",
                    field=models.CharField(blank=True, default="manual", max_length=32),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ticket",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("qr_asset_troubleshooting", "QR Asset Troubleshooting"),
                    ("qr_asset_manual_report", "QR Asset Manual Report"),
                ],
                default="manual",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="troubleshooting_attempted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ticket",
            name="troubleshooting_problem",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="ticket",
            name="troubleshooting_result",
            field=models.CharField(
                choices=[
                    ("not_attempted", "Not Attempted"),
                    ("failed", "Failed"),
                    ("skipped", "Skipped"),
                ],
                default="not_attempted",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="troubleshooting_steps_completed",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name="AssetCommonProblem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("asset_type", models.CharField(blank=True, db_index=True, default="", max_length=120)),
                ("asset_category", models.CharField(blank=True, db_index=True, default="", max_length=120)),
                ("title", models.CharField(max_length=180)),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "asset_common_problems",
                "ordering": ["asset_type", "asset_category", "title"],
                "indexes": [
                    models.Index(fields=["asset_type", "is_active"], name="asset_problem_type_idx"),
                    models.Index(fields=["asset_category", "is_active"], name="asset_problem_cat_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("asset_type", "asset_category", "title"),
                        name="unique_asset_problem_scope_title",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AssetQrScan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("asset_code", models.CharField(db_index=True, max_length=120)),
                ("source", models.CharField(blank=True, default="asset_qr_flow", max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="qr_scans",
                        to="core.consumable",
                    ),
                ),
            ],
            options={
                "db_table": "asset_qr_scans",
                "ordering": ["-created_at", "-id"],
                "indexes": [models.Index(fields=["asset_code", "created_at"], name="asset_qr_code_at_idx")],
            },
        ),
        migrations.CreateModel(
            name="TroubleshootingResolution",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("asset_code", models.CharField(blank=True, db_index=True, default="", max_length=120)),
                ("problem_title", models.CharField(max_length=180)),
                ("completed_steps", models.JSONField(blank=True, default=list)),
                (
                    "resolution_status",
                    models.CharField(choices=[("solved", "Solved"), ("failed", "Failed"), ("skipped", "Skipped")], max_length=20),
                ),
                (
                    "solved_by",
                    models.CharField(
                        choices=[
                            ("system_guided_troubleshooting", "LEC IntelliSupport Guided Troubleshooting"),
                            ("user", "User"),
                            ("technician", "Technician"),
                        ],
                        default="system_guided_troubleshooting",
                        max_length=64,
                    ),
                ),
                (
                    "solved_by_display",
                    models.CharField(blank=True, default="LEC IntelliSupport Guided Troubleshooting", max_length=120),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("qr_asset_troubleshooting", "QR Asset Troubleshooting"),
                            ("qr_asset_manual_report", "QR Asset Manual Report"),
                            ("manual", "Manual"),
                        ],
                        default="qr_asset_troubleshooting",
                        max_length=64,
                    ),
                ),
                ("branch", models.CharField(blank=True, default="", max_length=120)),
                ("department", models.CharField(blank=True, default="", max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="troubleshooting_resolutions",
                        to="core.consumable",
                    ),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolutions",
                        to="core.assetcommonproblem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="troubleshooting_resolutions",
                        to="core.user",
                    ),
                ),
            ],
            options={
                "db_table": "troubleshooting_resolutions",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(fields=["resolution_status", "created_at"], name="trouble_res_status_at_idx"),
                    models.Index(fields=["asset_code", "resolution_status"], name="trouble_res_asset_status_idx"),
                    models.Index(fields=["problem_title", "created_at"], name="trouble_res_problem_at_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="TroubleshootingStep",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("step_number", models.PositiveIntegerField()),
                ("instruction", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="core.assetcommonproblem",
                    ),
                ),
            ],
            options={
                "db_table": "troubleshooting_steps",
                "ordering": ["problem_id", "step_number", "id"],
                "constraints": [
                    models.UniqueConstraint(fields=("problem", "step_number"), name="unique_problem_step_number"),
                ],
            },
        ),
        migrations.RunPython(seed_asset_troubleshooting_data, migrations.RunPython.noop),
    ]
